I 2020-04-02 19:06:05 Starting Context Server.)
I 2020-04-02 19:06:09 Server Interrupted.)
I 2020-04-02 19:06:09 Stopped Server.)
I 2020-04-02 19:07:21 Starting Context Server.)
I 2020-04-02 19:07:22 Server Interrupted.)
I 2020-04-02 19:07:22 Stopped Server.)
I 2020-04-02 19:07:51 Starting Context Server.)
I 2020-04-02 19:07:53 Server Interrupted.)
I 2020-04-02 19:07:53 Stopped Server.)
I 2020-04-02 19:21:04 Starting Context Server.)
I 2020-04-02 19:24:44 Server Interrupted.)
I 2020-04-02 19:24:44 Stopped Server.)
I 2020-04-02 19:24:46 Starting Context Server.)
I 2020-04-02 20:02:50 Server Interrupted.)
I 2020-04-02 20:02:50 Stopped Server.)
I 2020-04-02 20:14:42 Starting Context Server.)
I 2020-04-02 20:14:50 Server Interrupted.)
I 2020-04-02 20:14:50 Stopped Server.)
I 2020-04-02 20:23:06 Starting Context Server.)
I 2020-04-02 20:24:50 Server Interrupted.)
I 2020-04-02 20:24:50 Stopped Server.)
I 2020-04-02 20:25:14 Starting Context Server.)
I 2020-04-02 20:36:25 Server Interrupted.)
I 2020-04-02 20:36:25 Stopped Server.)
I 2020-04-02 20:36:57 Starting Context Server.)
I 2020-04-02 20:37:03 Server Interrupted.)
I 2020-04-02 20:37:03 Stopped Server.)
I 2020-04-02 20:37:05 Starting Context Server.)
I 2020-04-02 20:43:57 Server Interrupted.)
I 2020-04-02 20:43:57 Stopped Server.)
I 2020-04-03 21:26:06 Starting Context Server.)
I 2020-04-03 21:27:35 Server Interrupted.)
I 2020-04-03 21:27:35 Stopped Server.)
I 2020-04-03 21:27:52 Starting Context Server.)
I 2020-04-04 00:18:47 Server Interrupted.)
I 2020-04-04 00:18:47 Stopped Server.)
I 2020-04-04 00:18:52 Starting Context Server.)
E 2020-04-04 00:24:19 Error in receiving data in server)
E 2020-04-04 00:24:34 Error in receiving data in server)
E 2020-04-04 00:25:28 Error in receiving data in server)
I 2020-04-04 00:26:00 Server Interrupted.)
I 2020-04-04 00:26:00 Stopped Server.)
I 2020-04-04 00:32:09 Starting Context Server.)
E 2020-04-04 00:32:12 Error in receiving data in server)
E 2020-04-04 00:35:58 Error in receiving data in server)
I 2020-04-04 00:36:52 Server Interrupted.)
I 2020-04-04 00:36:52 Stopped Server.)
I 2020-04-04 00:36:53 Starting Context Server.)
E 2020-04-04 00:36:55 Error in receiving data in server)
I 2020-04-04 00:37:32 Server Interrupted.)
I 2020-04-04 00:37:32 Stopped Server.)
I 2020-04-04 00:38:48 Starting Context Server.)
I 2020-04-04 01:08:18 Server Interrupted.)
I 2020-04-04 01:08:18 Stopped Server.)
I 2020-04-04 01:08:20 Starting Context Server.)
I 2020-04-04 01:12:39 Server Interrupted.)
I 2020-04-04 01:12:39 Stopped Server.)
I 2020-04-04 01:12:40 Starting Context Server.)
I 2020-04-04 01:14:13 Server Interrupted.)
I 2020-04-04 01:14:13 Stopped Server.)
I 2020-04-04 01:47:54 Starting Context Server.)
I 2020-04-04 02:04:46 Starting Context Server.)
I 2020-04-04 02:15:13 Starting Context Server.)
I 2020-04-04 18:07:59 Starting Context Server.)
I 2020-04-04 18:16:00 Server Interrupted.)
I 2020-04-04 18:16:00 Stopped Server.)
I 2020-04-04 19:40:54 Starting Context Server.)
E 2020-04-04 19:42:01 Bad client request)
I 2020-04-04 19:47:01 Server Interrupted.)
I 2020-04-04 19:47:01 Stopped Server.)
I 2020-04-04 19:47:03 Starting Context Server.)
E 2020-04-04 19:47:14 Bad client request)
E 2020-04-04 19:47:44 Bad client request)
I 2020-04-04 21:00:38 Server Interrupted.)
I 2020-04-04 21:00:38 Stopped Server.)
I 2020-04-04 22:13:39 Starting Context Server.)
I 2020-04-04 22:13:40 Server Interrupted.)
I 2020-04-04 22:13:40 Stopped Server.)
I 2020-04-04 22:13:51 Starting Context Server.)
I 2020-04-04 22:15:20 Server Interrupted.)
I 2020-04-04 22:15:20 Stopped Server.)
I 2020-04-04 22:15:24 Starting Context Server.)
E 2020-04-04 22:15:34 Error in receiving data in server)
I 2020-04-04 22:15:35 Server Interrupted.)
I 2020-04-04 22:15:35 Stopped Server.)
I 2020-04-04 22:16:54 Starting Context Server.)
E 2020-04-04 22:17:03 Error in receiving data in server)
I 2020-04-04 22:17:06 Server Interrupted.)
I 2020-04-04 22:17:06 Stopped Server.)
I 2020-04-04 22:17:27 Starting Context Server.)
E 2020-04-04 22:17:35 Bad client request)
I 2020-04-04 22:17:38 Server Interrupted.)
I 2020-04-04 22:17:38 Stopped Server.)
I 2020-04-04 22:18:35 Starting Context Server.)
E 2020-04-04 22:18:43 Bad client request)
I 2020-04-04 22:18:59 Server Interrupted.)
I 2020-04-04 22:18:59 Stopped Server.)
I 2020-04-04 22:19:00 Starting Context Server.)
E 2020-04-04 22:19:09 Bad client request)
I 2020-04-04 22:19:44 Server Interrupted.)
I 2020-04-04 22:19:44 Stopped Server.)
I 2020-04-04 22:20:00 Starting Context Server.)
E 2020-04-04 22:20:02 Bad client request)
E 2020-04-04 22:20:02 Bad client request)
E 2020-04-04 22:20:09 Bad client request)
E 2020-04-04 22:20:09 Bad client request)
I 2020-04-04 22:20:33 Server Interrupted.)
I 2020-04-04 22:20:33 Stopped Server.)
I 2020-04-04 22:20:34 Starting Context Server.)
E 2020-04-04 22:20:36 Error in receiving data in server)
E 2020-04-04 22:20:43 Error in receiving data in server)
E 2020-04-04 22:21:00 Error in receiving data in server)
E 2020-04-04 22:21:06 Error in receiving data in server)
I 2020-04-04 22:21:40 Server Interrupted.)
I 2020-04-04 22:21:40 Stopped Server.)
I 2020-04-04 22:21:47 Starting Context Server.)
E 2020-04-04 22:21:50 Error in receiving data in server)
E 2020-04-04 22:21:57 Error in receiving data in server)
I 2020-04-04 22:22:47 Server Interrupted.)
I 2020-04-04 22:22:47 Stopped Server.)
I 2020-04-04 22:22:50 Starting Context Server.)
E 2020-04-04 22:22:51 Error in receiving data in server)
E 2020-04-04 22:22:58 Error in receiving data in server)
I 2020-04-04 22:23:16 Server Interrupted.)
I 2020-04-04 22:23:16 Stopped Server.)
I 2020-04-04 22:23:26 Starting Context Server.)
E 2020-04-04 22:23:29 Error in receiving data in server)
E 2020-04-04 22:23:35 Error in receiving data in server)
I 2020-04-04 22:24:41 Server Interrupted.)
I 2020-04-04 22:24:41 Stopped Server.)
I 2020-04-04 22:24:46 Starting Context Server.)
E 2020-04-04 22:24:54 Error in receiving data in server)
I 2020-04-04 22:27:22 Server Interrupted.)
I 2020-04-04 22:27:22 Stopped Server.)
I 2020-04-04 22:27:24 Starting Context Server.)
E 2020-04-04 22:27:31 Error in receiving data in server)
E 2020-04-04 22:29:39 Error in receiving data in server)
E 2020-04-04 22:30:34 Error in receiving data in server)
I 2020-04-04 22:30:38 Server Interrupted.)
I 2020-04-04 22:30:38 Stopped Server.)
I 2020-04-04 22:30:41 Starting Context Server.)
E 2020-04-04 22:30:48 Error in receiving data in server)
I 2020-04-04 22:33:59 Server Interrupted.)
I 2020-04-04 22:33:59 Stopped Server.)
I 2020-04-04 22:34:02 Starting Context Server.)
E 2020-04-04 22:34:08 Error in receiving data in server)
I 2020-04-04 22:35:18 Server Interrupted.)
I 2020-04-04 22:35:18 Stopped Server.)
I 2020-04-04 22:35:24 Starting Context Server.)
I 2020-04-04 22:40:48 Server Interrupted.)
I 2020-04-04 22:40:48 Stopped Server.)
I 2020-04-04 22:40:49 Starting Context Server.)
E 2020-04-04 22:40:51 Bad client request)
I 2020-04-04 22:41:09 Server Interrupted.)
I 2020-04-04 22:41:09 Stopped Server.)
I 2020-04-04 22:44:13 Starting Context Server.)
E 2020-04-04 22:44:17 Bad client request)
E 2020-04-04 22:44:40 Bad client request)
I 2020-04-04 22:45:17 Server Interrupted.)
I 2020-04-04 22:45:17 Stopped Server.)
I 2020-04-04 22:45:39 Starting Context Server.)
E 2020-04-04 22:45:47 Bad client request)
I 2020-04-04 22:46:40 Server Interrupted.)
I 2020-04-04 22:46:40 Stopped Server.)
I 2020-04-04 22:46:45 Starting Context Server.)
E 2020-04-04 22:46:52 Bad client request)
I 2020-04-04 22:47:48 Server Interrupted.)
I 2020-04-04 22:47:48 Stopped Server.)
I 2020-04-04 22:47:49 Starting Context Server.)
E 2020-04-04 22:47:51 Bad client request)
E 2020-04-04 22:47:51 Bad client request)
E 2020-04-04 22:47:57 Bad client request)
E 2020-04-04 22:47:57 Bad client request)
I 2020-04-04 22:49:00 Server Interrupted.)
I 2020-04-04 22:49:00 Stopped Server.)
I 2020-04-04 22:49:02 Starting Context Server.)
I 2020-04-04 22:49:30 Server Interrupted.)
I 2020-04-04 22:49:30 Stopped Server.)
I 2020-04-04 22:49:32 Starting Context Server.)
E 2020-04-04 22:49:40 Error in receiving data in server)
I 2020-04-04 22:49:49 Server Interrupted.)
I 2020-04-04 22:49:49 Stopped Server.)
I 2020-04-04 22:49:54 Starting Context Server.)
E 2020-04-04 22:50:02 Error in receiving data in server)
I 2020-04-04 22:50:07 Server Interrupted.)
I 2020-04-04 22:50:07 Stopped Server.)
I 2020-04-04 22:50:44 Starting Context Server.)
E 2020-04-04 22:50:51 Error in receiving data in server)
I 2020-04-04 22:51:36 Server Interrupted.)
I 2020-04-04 22:51:36 Stopped Server.)
I 2020-04-04 22:51:37 Starting Context Server.)
E 2020-04-04 22:51:45 Error in receiving data in server)
I 2020-04-04 22:57:46 Server Interrupted.)
I 2020-04-04 22:57:46 Stopped Server.)
I 2020-04-04 22:57:48 Starting Context Server.)
E 2020-04-04 22:57:56 Error in receiving data in server)
I 2020-04-04 22:59:05 Server Interrupted.)
I 2020-04-04 22:59:05 Stopped Server.)
I 2020-04-04 22:59:19 Starting Context Server.)
E 2020-04-04 22:59:27 Error in receiving data in server)
I 2020-04-04 22:59:30 Server Interrupted.)
I 2020-04-04 22:59:30 Stopped Server.)
I 2020-04-04 23:00:46 Starting Context Server.)
E 2020-04-04 23:00:55 Error in receiving data in server)
I 2020-04-04 23:01:52 Server Interrupted.)
I 2020-04-04 23:01:52 Stopped Server.)
I 2020-04-04 23:01:54 Starting Context Server.)
E 2020-04-04 23:02:01 Error in receiving data in server)
I 2020-04-04 23:02:37 Server Interrupted.)
I 2020-04-04 23:02:37 Stopped Server.)
I 2020-04-04 23:02:41 Starting Context Server.)
I 2020-04-04 23:02:57 Server Interrupted.)
I 2020-04-04 23:02:57 Stopped Server.)
I 2020-04-04 23:13:56 Starting Context Server.)
E 2020-04-04 23:14:04 Error in receiving data in server)
E 2020-04-04 23:14:10 Error in receiving data in server)
I 2020-04-04 23:14:13 Server Interrupted.)
I 2020-04-04 23:14:13 Stopped Server.)
I 2020-04-04 23:14:36 Starting Context Server.)
E 2020-04-04 23:15:33 Error in receiving data in server)
I 2020-04-04 23:15:36 Server Interrupted.)
I 2020-04-04 23:15:36 Stopped Server.)
I 2020-04-04 23:17:07 Starting Context Server.)
I 2020-04-04 23:18:42 Server Interrupted.)
I 2020-04-04 23:18:42 Stopped Server.)
I 2020-04-04 23:19:46 Starting Context Server.)
I 2020-04-04 23:19:53 Server Interrupted.)
I 2020-04-04 23:19:53 Stopped Server.)
I 2020-04-04 23:25:24 Starting Context Server.)
E 2020-04-04 23:25:30 Error in receiving data in server)
E 2020-04-04 23:25:34 Error in receiving data in server)
I 2020-04-04 23:25:35 Server Interrupted.)
I 2020-04-04 23:25:35 Stopped Server.)
I 2020-04-04 23:26:06 Starting Context Server.)
I 2020-04-04 23:32:38 Server Interrupted.)
I 2020-04-04 23:32:38 Stopped Server.)
D 2020-04-07 03:05:53 Using EPollPoller)
D 2020-04-07 03:05:53 Created default connection workflow <pika.adapters.utils.connection_workflow.AMQPConnectionWorkflow object at 0x7f075b3f11c0>)
D 2020-04-07 03:05:53 Starting AMQP Connection workflow asynchronously.)
D 2020-04-07 03:05:53 call_later: added timeout <pika.adapters.select_connection._Timeout object at 0x7f075b3f11f0> with deadline=6016.587634011 and callback=functools.partial(<bound method AMQPConnectionWorkflow._start_new_cycle_async of <pika.adapters.utils.connection_workflow.AMQPConnectionWorkflow object at 0x7f075b3f11c0>>, first=True); now=6016.587634011; delay=0)
D 2020-04-07 03:05:53 Beginning a new AMQP connection workflow cycle; attempts remaining after this: 0)
D 2020-04-07 03:05:53 call_later: added timeout <pika.adapters.select_connection._Timeout object at 0x7f075b3f1220> with deadline=6016.587859375 and callback=<bound method AMQPConnectionWorkflow._try_next_config_async of <pika.adapters.utils.connection_workflow.AMQPConnectionWorkflow object at 0x7f075b3f11c0>>; now=6016.587859375; delay=0)
D 2020-04-07 03:05:53 _try_next_config_async: 'localhost':5672)
D 2020-04-07 03:05:53 process_timeouts: invoking callback=<bound method _AddressResolver._dispatch_result of <pika.adapters.utils.selector_ioloop_adapter._AddressResolver object at 0x7f075b3f1250>>)
D 2020-04-07 03:05:53 Invoking asynchronous getaddrinfo() completion callback; host='localhost')
D 2020-04-07 03:05:53 getaddrinfo returned 1 records)
D 2020-04-07 03:05:53 Attempting to connect using address record (<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('127.0.0.1', 5672)))
I 2020-04-07 03:05:53 Pika version 1.1.0 connecting to ('127.0.0.1', 5672))
D 2020-04-07 03:05:53 add_callback_threadsafe: added callback=<bound method _AddressResolver._dispatch_result of <pika.adapters.utils.selector_ioloop_adapter._AddressResolver object at 0x7f075b3f1250>>)
D 2020-04-07 03:05:53 add_callback_threadsafe: added callback=<bound method _AsyncSocketConnector._start_async of <pika.adapters.utils.io_services_utils._AsyncSocketConnector object at 0x7f075b3f15e0>>)
D 2020-04-07 03:05:53 call_later: added timeout <pika.adapters.select_connection._Timeout object at 0x7f075b3f15b0> with deadline=6026.602746075 and callback=<bound method AMQPConnector._on_tcp_connection_timeout of <pika.adapters.utils.connection_workflow.AMQPConnector object at 0x7f075b3f1850>>; now=6016.602746075; delay=10.0)
D 2020-04-07 03:05:53 call_later: added timeout <pika.adapters.select_connection._Timeout object at 0x7f075b3f1970> with deadline=6031.602813137 and callback=<bound method AMQPConnector._on_overall_timeout of <pika.adapters.utils.connection_workflow.AMQPConnector object at 0x7f075b3f1850>>; now=6016.602813137; delay=15.0)
D 2020-04-07 03:05:53 process_timeouts: invoking callback=<bound method _AsyncSocketConnector._start_async of <pika.adapters.utils.io_services_utils._AsyncSocketConnector object at 0x7f075b3f15e0>>)
D 2020-04-07 03:05:53 SelectorIOServicesAdapter.set_writer(7, <bound method _AsyncSocketConnector._on_writable of <pika.adapters.utils.io_services_utils._AsyncSocketConnector object at 0x7f075b3f15e0>>))
D 2020-04-07 03:05:53 set_writer(7, _) added handler Wr)
D 2020-04-07 03:05:53 Connection-establishment is in progress for <socket.socket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 44456)>.)
E 2020-04-07 03:05:53 Socket failed to connect: <socket.socket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 44456)>; error=111 (Connection refused))
D 2020-04-07 03:05:53 _AsyncSocketConnector._report_completion(ConnectionRefusedError(111, 'Connection refused')); <socket.socket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 44456)>)
D 2020-04-07 03:05:53 SelectorIOServicesAdapter.remove_writer(7))
D 2020-04-07 03:05:53 remove_writer(7) removed handler)
D 2020-04-07 03:05:53 remove_timeout: removing timeout <pika.adapters.select_connection._Timeout object at 0x7f075b3f15b0> with deadline=6026.602746075 and callback=<bound method AMQPConnector._on_tcp_connection_timeout of <pika.adapters.utils.connection_workflow.AMQPConnector object at 0x7f075b3f1850>>)
E 2020-04-07 03:05:53 TCP Connection attempt failed: ConnectionRefusedError(111, 'Connection refused'); dest=(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('127.0.0.1', 5672)))
E 2020-04-07 03:05:53 AMQPConnector - reporting failure: AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'))
D 2020-04-07 03:05:53 remove_timeout: removing timeout <pika.adapters.select_connection._Timeout object at 0x7f075b3f1970> with deadline=6031.602813137 and callback=<bound method AMQPConnector._on_overall_timeout of <pika.adapters.utils.connection_workflow.AMQPConnector object at 0x7f075b3f1850>>)
D 2020-04-07 03:05:53 Connection attempt completed with AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'))
D 2020-04-07 03:05:53 _try_next_resolved_address: continuing with next config.)
D 2020-04-07 03:05:53 _try_next_config_async: starting a new cycle.)
E 2020-04-07 03:05:53 AMQP connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - None.)
E 2020-04-07 03:05:53 AMQPConnectionWorkflow - reporting failure: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - None)
E 2020-04-07 03:05:53 Connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - None)
E 2020-04-07 03:05:53 Error in _create_connection().)
Traceback (most recent call last):
  File "/home/user/Desktop/cortex/.env/lib/python3.8/site-packages/pika/adapters/blocking_connection.py", line 450, in _create_connection
    raise self._reap_last_connection_workflow_error(error)
pika.exceptions.AMQPConnectionError
D 2020-04-07 03:07:19 Using EPollPoller)
D 2020-04-07 03:07:19 Created default connection workflow <pika.adapters.utils.connection_workflow.AMQPConnectionWorkflow object at 0x7f9fa865e1c0>)
D 2020-04-07 03:07:19 Starting AMQP Connection workflow asynchronously.)
D 2020-04-07 03:07:19 call_later: added timeout <pika.adapters.select_connection._Timeout object at 0x7f9fa865e1f0> with deadline=6102.905198784 and callback=functools.partial(<bound method AMQPConnectionWorkflow._start_new_cycle_async of <pika.adapters.utils.connection_workflow.AMQPConnectionWorkflow object at 0x7f9fa865e1c0>>, first=True); now=6102.905198784; delay=0)
D 2020-04-07 03:07:19 Beginning a new AMQP connection workflow cycle; attempts remaining after this: 0)
D 2020-04-07 03:07:19 call_later: added timeout <pika.adapters.select_connection._Timeout object at 0x7f9fa865e220> with deadline=6102.905344827 and callback=<bound method AMQPConnectionWorkflow._try_next_config_async of <pika.adapters.utils.connection_workflow.AMQPConnectionWorkflow object at 0x7f9fa865e1c0>>; now=6102.905344827; delay=0)
D 2020-04-07 03:07:19 _try_next_config_async: 'localhost':5672)
D 2020-04-07 03:07:19 process_timeouts: invoking callback=<bound method _AddressResolver._dispatch_result of <pika.adapters.utils.selector_ioloop_adapter._AddressResolver object at 0x7f9fa865e250>>)
D 2020-04-07 03:07:19 Invoking asynchronous getaddrinfo() completion callback; host='localhost')
D 2020-04-07 03:07:19 getaddrinfo returned 1 records)
D 2020-04-07 03:07:19 Attempting to connect using address record (<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('127.0.0.1', 5672)))
I 2020-04-07 03:07:19 Pika version 1.1.0 connecting to ('127.0.0.1', 5672))
D 2020-04-07 03:07:19 add_callback_threadsafe: added callback=<bound method _AddressResolver._dispatch_result of <pika.adapters.utils.selector_ioloop_adapter._AddressResolver object at 0x7f9fa865e250>>)
D 2020-04-07 03:07:19 add_callback_threadsafe: added callback=<bound method _AsyncSocketConnector._start_async of <pika.adapters.utils.io_services_utils._AsyncSocketConnector object at 0x7f9fa865e5e0>>)
D 2020-04-07 03:07:19 call_later: added timeout <pika.adapters.select_connection._Timeout object at 0x7f9fa865e5b0> with deadline=6112.908533605 and callback=<bound method AMQPConnector._on_tcp_connection_timeout of <pika.adapters.utils.connection_workflow.AMQPConnector object at 0x7f9fa865e850>>; now=6102.908533605; delay=10.0)
D 2020-04-07 03:07:19 call_later: added timeout <pika.adapters.select_connection._Timeout object at 0x7f9fa865e970> with deadline=6117.908611417 and callback=<bound method AMQPConnector._on_overall_timeout of <pika.adapters.utils.connection_workflow.AMQPConnector object at 0x7f9fa865e850>>; now=6102.908611417; delay=15.0)
D 2020-04-07 03:07:19 process_timeouts: invoking callback=<bound method _AsyncSocketConnector._start_async of <pika.adapters.utils.io_services_utils._AsyncSocketConnector object at 0x7f9fa865e5e0>>)
D 2020-04-07 03:07:19 SelectorIOServicesAdapter.set_writer(7, <bound method _AsyncSocketConnector._on_writable of <pika.adapters.utils.io_services_utils._AsyncSocketConnector object at 0x7f9fa865e5e0>>))
D 2020-04-07 03:07:19 set_writer(7, _) added handler Wr)
D 2020-04-07 03:07:19 Connection-establishment is in progress for <socket.socket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 44460)>.)
E 2020-04-07 03:07:19 Socket failed to connect: <socket.socket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 44460)>; error=111 (Connection refused))
D 2020-04-07 03:07:19 _AsyncSocketConnector._report_completion(ConnectionRefusedError(111, 'Connection refused')); <socket.socket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 44460)>)
D 2020-04-07 03:07:19 SelectorIOServicesAdapter.remove_writer(7))
D 2020-04-07 03:07:19 remove_writer(7) removed handler)
D 2020-04-07 03:07:19 remove_timeout: removing timeout <pika.adapters.select_connection._Timeout object at 0x7f9fa865e5b0> with deadline=6112.908533605 and callback=<bound method AMQPConnector._on_tcp_connection_timeout of <pika.adapters.utils.connection_workflow.AMQPConnector object at 0x7f9fa865e850>>)
E 2020-04-07 03:07:19 TCP Connection attempt failed: ConnectionRefusedError(111, 'Connection refused'); dest=(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('127.0.0.1', 5672)))
E 2020-04-07 03:07:19 AMQPConnector - reporting failure: AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'))
D 2020-04-07 03:07:19 remove_timeout: removing timeout <pika.adapters.select_connection._Timeout object at 0x7f9fa865e970> with deadline=6117.908611417 and callback=<bound method AMQPConnector._on_overall_timeout of <pika.adapters.utils.connection_workflow.AMQPConnector object at 0x7f9fa865e850>>)
D 2020-04-07 03:07:19 Connection attempt completed with AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'))
D 2020-04-07 03:07:19 _try_next_resolved_address: continuing with next config.)
D 2020-04-07 03:07:19 _try_next_config_async: starting a new cycle.)
E 2020-04-07 03:07:19 AMQP connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - None.)
E 2020-04-07 03:07:19 AMQPConnectionWorkflow - reporting failure: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - None)
E 2020-04-07 03:07:19 Connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - None)
E 2020-04-07 03:07:19 Error in _create_connection().)
Traceback (most recent call last):
  File "/home/user/Desktop/cortex/.env/lib/python3.8/site-packages/pika/adapters/blocking_connection.py", line 450, in _create_connection
    raise self._reap_last_connection_workflow_error(error)
pika.exceptions.AMQPConnectionError
D 2020-04-07 03:13:25 Using EPollPoller)
D 2020-04-07 03:13:25 Created default connection workflow <pika.adapters.utils.connection_workflow.AMQPConnectionWorkflow object at 0x7f5fc63051c0>)
D 2020-04-07 03:13:25 Starting AMQP Connection workflow asynchronously.)
D 2020-04-07 03:13:25 call_later: added timeout <pika.adapters.select_connection._Timeout object at 0x7f5fc63051f0> with deadline=6468.771287781 and callback=functools.partial(<bound method AMQPConnectionWorkflow._start_new_cycle_async of <pika.adapters.utils.connection_workflow.AMQPConnectionWorkflow object at 0x7f5fc63051c0>>, first=True); now=6468.771287781; delay=0)
D 2020-04-07 03:13:25 Beginning a new AMQP connection workflow cycle; attempts remaining after this: 0)
D 2020-04-07 03:13:25 call_later: added timeout <pika.adapters.select_connection._Timeout object at 0x7f5fc6305220> with deadline=6468.771436773 and callback=<bound method AMQPConnectionWorkflow._try_next_config_async of <pika.adapters.utils.connection_workflow.AMQPConnectionWorkflow object at 0x7f5fc63051c0>>; now=6468.771436773; delay=0)
D 2020-04-07 03:13:25 _try_next_config_async: 'localhost':5672)
D 2020-04-07 03:13:25 process_timeouts: invoking callback=<bound method _AddressResolver._dispatch_result of <pika.adapters.utils.selector_ioloop_adapter._AddressResolver object at 0x7f5fc6305250>>)
D 2020-04-07 03:13:25 Invoking asynchronous getaddrinfo() completion callback; host='localhost')
D 2020-04-07 03:13:25 getaddrinfo returned 1 records)
D 2020-04-07 03:13:25 Attempting to connect using address record (<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('127.0.0.1', 5672)))
I 2020-04-07 03:13:25 Pika version 1.1.0 connecting to ('127.0.0.1', 5672))
D 2020-04-07 03:13:25 add_callback_threadsafe: added callback=<bound method _AddressResolver._dispatch_result of <pika.adapters.utils.selector_ioloop_adapter._AddressResolver object at 0x7f5fc6305250>>)
D 2020-04-07 03:13:25 add_callback_threadsafe: added callback=<bound method _AsyncSocketConnector._start_async of <pika.adapters.utils.io_services_utils._AsyncSocketConnector object at 0x7f5fc63055e0>>)
D 2020-04-07 03:13:25 call_later: added timeout <pika.adapters.select_connection._Timeout object at 0x7f5fc63055b0> with deadline=6478.776261389 and callback=<bound method AMQPConnector._on_tcp_connection_timeout of <pika.adapters.utils.connection_workflow.AMQPConnector object at 0x7f5fc6305850>>; now=6468.776261389; delay=10.0)
D 2020-04-07 03:13:25 call_later: added timeout <pika.adapters.select_connection._Timeout object at 0x7f5fc6305970> with deadline=6483.776347953 and callback=<bound method AMQPConnector._on_overall_timeout of <pika.adapters.utils.connection_workflow.AMQPConnector object at 0x7f5fc6305850>>; now=6468.776347953; delay=15.0)
D 2020-04-07 03:13:25 process_timeouts: invoking callback=<bound method _AsyncSocketConnector._start_async of <pika.adapters.utils.io_services_utils._AsyncSocketConnector object at 0x7f5fc63055e0>>)
D 2020-04-07 03:13:25 SelectorIOServicesAdapter.set_writer(7, <bound method _AsyncSocketConnector._on_writable of <pika.adapters.utils.io_services_utils._AsyncSocketConnector object at 0x7f5fc63055e0>>))
D 2020-04-07 03:13:25 set_writer(7, _) added handler Wr)
D 2020-04-07 03:13:25 Connection-establishment is in progress for <socket.socket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 44466)>.)
E 2020-04-07 03:13:25 Socket failed to connect: <socket.socket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 44466)>; error=111 (Connection refused))
D 2020-04-07 03:13:25 _AsyncSocketConnector._report_completion(ConnectionRefusedError(111, 'Connection refused')); <socket.socket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 44466)>)
D 2020-04-07 03:13:25 SelectorIOServicesAdapter.remove_writer(7))
D 2020-04-07 03:13:25 remove_writer(7) removed handler)
D 2020-04-07 03:13:25 remove_timeout: removing timeout <pika.adapters.select_connection._Timeout object at 0x7f5fc63055b0> with deadline=6478.776261389 and callback=<bound method AMQPConnector._on_tcp_connection_timeout of <pika.adapters.utils.connection_workflow.AMQPConnector object at 0x7f5fc6305850>>)
E 2020-04-07 03:13:25 TCP Connection attempt failed: ConnectionRefusedError(111, 'Connection refused'); dest=(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('127.0.0.1', 5672)))
E 2020-04-07 03:13:25 AMQPConnector - reporting failure: AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'))
D 2020-04-07 03:13:25 remove_timeout: removing timeout <pika.adapters.select_connection._Timeout object at 0x7f5fc6305970> with deadline=6483.776347953 and callback=<bound method AMQPConnector._on_overall_timeout of <pika.adapters.utils.connection_workflow.AMQPConnector object at 0x7f5fc6305850>>)
D 2020-04-07 03:13:25 Connection attempt completed with AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'))
D 2020-04-07 03:13:25 _try_next_resolved_address: continuing with next config.)
D 2020-04-07 03:13:25 _try_next_config_async: starting a new cycle.)
E 2020-04-07 03:13:25 AMQP connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - None.)
E 2020-04-07 03:13:25 AMQPConnectionWorkflow - reporting failure: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - None)
E 2020-04-07 03:13:25 Connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - None)
E 2020-04-07 03:13:25 Error in _create_connection().)
Traceback (most recent call last):
  File "/home/user/Desktop/cortex/.env/lib/python3.8/site-packages/pika/adapters/blocking_connection.py", line 450, in _create_connection
    raise self._reap_last_connection_workflow_error(error)
pika.exceptions.AMQPConnectionError
D 2020-04-07 03:14:25 Using EPollPoller)
D 2020-04-07 03:14:25 Created default connection workflow <pika.adapters.utils.connection_workflow.AMQPConnectionWorkflow object at 0x7fd3fc4b81c0>)
D 2020-04-07 03:14:25 Starting AMQP Connection workflow asynchronously.)
D 2020-04-07 03:14:25 call_later: added timeout <pika.adapters.select_connection._Timeout object at 0x7fd3fc4b81f0> with deadline=6529.068897755 and callback=functools.partial(<bound method AMQPConnectionWorkflow._start_new_cycle_async of <pika.adapters.utils.connection_workflow.AMQPConnectionWorkflow object at 0x7fd3fc4b81c0>>, first=True); now=6529.068897755; delay=0)
D 2020-04-07 03:14:25 Beginning a new AMQP connection workflow cycle; attempts remaining after this: 0)
D 2020-04-07 03:14:25 call_later: added timeout <pika.adapters.select_connection._Timeout object at 0x7fd3fc4b8220> with deadline=6529.069038492 and callback=<bound method AMQPConnectionWorkflow._try_next_config_async of <pika.adapters.utils.connection_workflow.AMQPConnectionWorkflow object at 0x7fd3fc4b81c0>>; now=6529.069038492; delay=0)
D 2020-04-07 03:14:25 _try_next_config_async: 'localhost':5672)
D 2020-04-07 03:14:25 process_timeouts: invoking callback=<bound method _AddressResolver._dispatch_result of <pika.adapters.utils.selector_ioloop_adapter._AddressResolver object at 0x7fd3fc4b8250>>)
D 2020-04-07 03:14:25 Invoking asynchronous getaddrinfo() completion callback; host='localhost')
D 2020-04-07 03:14:25 getaddrinfo returned 1 records)
D 2020-04-07 03:14:25 Attempting to connect using address record (<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('127.0.0.1', 5672)))
I 2020-04-07 03:14:25 Pika version 1.1.0 connecting to ('127.0.0.1', 5672))
D 2020-04-07 03:14:25 add_callback_threadsafe: added callback=<bound method _AddressResolver._dispatch_result of <pika.adapters.utils.selector_ioloop_adapter._AddressResolver object at 0x7fd3fc4b8250>>)
D 2020-04-07 03:14:25 add_callback_threadsafe: added callback=<bound method _AsyncSocketConnector._start_async of <pika.adapters.utils.io_services_utils._AsyncSocketConnector object at 0x7fd3fc4b85e0>>)
D 2020-04-07 03:14:25 call_later: added timeout <pika.adapters.select_connection._Timeout object at 0x7fd3fc4b85b0> with deadline=6539.071825208 and callback=<bound method AMQPConnector._on_tcp_connection_timeout of <pika.adapters.utils.connection_workflow.AMQPConnector object at 0x7fd3fc4b8850>>; now=6529.071825208; delay=10.0)
D 2020-04-07 03:14:25 call_later: added timeout <pika.adapters.select_connection._Timeout object at 0x7fd3fc4b8970> with deadline=6544.071872641 and callback=<bound method AMQPConnector._on_overall_timeout of <pika.adapters.utils.connection_workflow.AMQPConnector object at 0x7fd3fc4b8850>>; now=6529.071872641; delay=15.0)
D 2020-04-07 03:14:25 process_timeouts: invoking callback=<bound method _AsyncSocketConnector._start_async of <pika.adapters.utils.io_services_utils._AsyncSocketConnector object at 0x7fd3fc4b85e0>>)
D 2020-04-07 03:14:25 SelectorIOServicesAdapter.set_writer(7, <bound method _AsyncSocketConnector._on_writable of <pika.adapters.utils.io_services_utils._AsyncSocketConnector object at 0x7fd3fc4b85e0>>))
D 2020-04-07 03:14:25 set_writer(7, _) added handler Wr)
D 2020-04-07 03:14:25 Connection-establishment is in progress for <socket.socket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 44470)>.)
E 2020-04-07 03:14:25 Socket failed to connect: <socket.socket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 44470)>; error=111 (Connection refused))
D 2020-04-07 03:14:25 _AsyncSocketConnector._report_completion(ConnectionRefusedError(111, 'Connection refused')); <socket.socket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 44470)>)
D 2020-04-07 03:14:25 SelectorIOServicesAdapter.remove_writer(7))
D 2020-04-07 03:14:25 remove_writer(7) removed handler)
D 2020-04-07 03:14:25 remove_timeout: removing timeout <pika.adapters.select_connection._Timeout object at 0x7fd3fc4b85b0> with deadline=6539.071825208 and callback=<bound method AMQPConnector._on_tcp_connection_timeout of <pika.adapters.utils.connection_workflow.AMQPConnector object at 0x7fd3fc4b8850>>)
E 2020-04-07 03:14:25 TCP Connection attempt failed: ConnectionRefusedError(111, 'Connection refused'); dest=(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('127.0.0.1', 5672)))
E 2020-04-07 03:14:25 AMQPConnector - reporting failure: AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'))
D 2020-04-07 03:14:25 remove_timeout: removing timeout <pika.adapters.select_connection._Timeout object at 0x7fd3fc4b8970> with deadline=6544.071872641 and callback=<bound method AMQPConnector._on_overall_timeout of <pika.adapters.utils.connection_workflow.AMQPConnector object at 0x7fd3fc4b8850>>)
D 2020-04-07 03:14:25 Connection attempt completed with AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'))
D 2020-04-07 03:14:25 _try_next_resolved_address: continuing with next config.)
D 2020-04-07 03:14:25 _try_next_config_async: starting a new cycle.)
E 2020-04-07 03:14:25 AMQP connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - None.)
E 2020-04-07 03:14:25 AMQPConnectionWorkflow - reporting failure: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - None)
E 2020-04-07 03:14:25 Connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - None)
E 2020-04-07 03:14:25 Error in _create_connection().)
Traceback (most recent call last):
  File "/home/user/Desktop/cortex/.env/lib/python3.8/site-packages/pika/adapters/blocking_connection.py", line 450, in _create_connection
    raise self._reap_last_connection_workflow_error(error)
pika.exceptions.AMQPConnectionError
